---
title: "Biogeochemistry and Fish"
format: html
editor: visual
bibliography: references.bib
---

## Biogeochem Overview

Applied goal: use archival tissues (eye lens, otolith, etc.), chemical tracers, and biochronologies to understand fish growth, diet, movement, and habitat needs. So, geochemical analysis (elements, isotopes) of archival biological tissues.

**Geochemistry**: applies chemistry to explain geological systems (Earth crust, oceans, atmosphere)

**Biogeochemistry**: study of how life, chemical processes, and the environment interact. Or, connections between the lithosphere, hydrosphere, and biosphere.

**Geochemical tracers**:

-   Elemental concentrations (Sr:Ca, SR:Ba, Fe, etc.)
-   Stable isotope ratios (Sr, O)

**Biological archival structures and tissues**:

-   calcified: otoliths, scales, vertebrae, fin rays, statoliths, shell, operculum
-   other: eye lenses

------------------------------------------------------------------------

## Strontium isotopes ratios (87Sr/86Sr)

-   Powerful geochemical tracers widely used across the sciences; reveal links the lithosphere, hydrosphere, and biosphere
    -   geology: rock weathering processes, sediment transport, hydro flow paths
    -   archaeology: human and animal migrations (skeletons and regions)
    -   aquatic science: trace fish movement across river systems
-   Riverine Sr isotope values vary considerably as a function of bedrock lithology
    -   including unconsolidated sediments and ages
    -   precisely reflected in the otolith composition; sequential records of chemistry
    -   quantitative reconstructions of natal origins and migratory pathways with high fidelity

------------------------------------------------------------------------

## Otoliths

-   Ear stone (used to detect sound; high density \~2.95 g/cm3)
-   Combined with lateral line, makes the octavolaateralis system (sound perception)
-   Slightly analogous to human ear bones
-   Made of CaCO~3~ (calcium carbonate, \>90%) and other organic matter (\~10%)
-   Not true bones, closer to stones
-   Sequentially built, daily and yearly rings
-   Key Uses:
    -   age, growth, shape analyses and species/stock identification (morphometrics),
    -   chemical approaches (microchemistry; lasers)

**Otolith microchemistry:** analyze trace elements and stable isotopes within fish ear bones

-   Combine with growth rate / ‘Omics to understand why
-   Info on percent of pop that migrates to different regions, and which are most successful
-   Info on marine survival rates

------------------------------------------------------------------------

## Sr isotope microchemistry lit review

1989: first study using otolith microchemistry (John Kalish, U Tasmania)

Riverine Sr values vary because of bedrock lithology

-   Capo et al. 1998, Palmer and Edmond 1992

First Sr / otolith papers:

-   @kennedy1997, @ingram1999

Reconstructions of their natal origins and migratory pathways:

-   @kennedy2002, @barnett-johnson2008, @Brennan2015, @sturrock2015

Inform conservation strategies:

-   @cordoleani2021, @dunnigan2023, @phillis2018, @zitek2023

Sr isoscapes for Sacramento River basin (discrete approach):

-   @barnett-johnson2007, @chen2025, @cordoleani2021a, @cordoleani2024, @hobson2010, @phillis2018a, @willmes2018, @willmes2021, @willmes2024

Continuous Approach:

-   combined modeling framework that integrates dendritic network models of 87Sr/86Sr variation across the river networks

### Chronological Review

@kennedy1997

-   first demonstrated potential for using Sr isotope ratios to discriminate among juvenile Atlantic salmon populations reared in 10 different tributaries in Vermont

@ingram1999

-   87Sr/86Sr ratios to determine natal origin for salmon in Scaramento-San Joaquin basin

@kennedy2000

-   reconstruct movement patterns and origin of individual juvenile Atlantic salmon in Connecticut River with high fidelity
-   formal overview of Sr as geochemical marker in fishes
-   context of isotopic turnover in fish, fish movements, and regional geology

@kennedy2002

-   reconstruct life history of four returning adult Atlantic salmon
-   natal origins and migratory pathways

@bacon2004

-   Sr and Sr/Ca to reconstruct migration and rearing histories of Chinook salmon

@barnett-johnson2008

-   linking Sr and otoliths with landscape geology in CA Central Valley system
-   natal origins and migratory pathways

Gibson-Reinemer et al., 2009

-   elemental and isotopic concentrations to detect origin and movement in hatchery rainbow trout in Wyoming and Colorado

Barnett-Johnson et al., 2010

-   multi-locus genotypes (microsats) and otolith 87Sr/86Sr ratios collected on the same individuals were complementary markers when applied in a hierarchy
-   microsats assigned fish to upper Columbia River Su/F genetic group
-   Sr provided finer-scale assignment to 5 natal river and hatchery groups
-   “Stock identification at the scales of individual rivers and hatcheries would help elucidate the abundance, distribution, and the relative contributions of natal sources important for the recovery and spatial management of Chinook salmon”

Miller et al., 2011

-   Chemical and structural composition of modern / archaeological otoliths from Upper Columbia
-   Found similarly between old and modern summer-fall run Chinook
-   Possible to maintain pre-developmental life histories with strategic management

Bataille and Bowen, 2012

-   Mapped large-scale 87Sr/86Sr variation in bedrock and water across CONUS that include the combined effects of geology and time
-   Fit bedrock model to predict rock Sr, then predict water Sr from weathering rates and Sr content
-   Has MFSR-ish area at 0.707 to 0.709

Hamann and Kennedy, (2012)

-   Big Creek, MFSR, juvenile dispersal affects straying in Chinook salmon
-   Used Sr87/Sr86 to reconstruct migratory/movement behavior of adults

Brennan et al., (2026)

-   SSN Sr isoscape for Sacramento River basin
-   identifies natal and rearing tributaries missed by discrete approaches

------------------------------------------------------------------------

## References
